JoranAngevaare/dddm

- DirectDmTargets/detector.py
Add superCDMS (Ge only) on the basis of  # https://arxiv.org/abs/1610.00006. (Si not being implemented in wimprates.)
> add super CDMS to detectors

- .github/dependabot.yml
To keep the actions up to date, dependabot is a nice feature to add
> Use dependabot for actions

- .github/workflows/test_package.yml
- DirectDmTargets/__init__.py
- DirectDmTargets/context.py
- DirectDmTargets/detector.py
- DirectDmTargets/emcee_applications.py
- DirectDmTargets/halo.py
- DirectDmTargets/nested_sampling.py
- DirectDmTargets/plot_basics.py
- DirectDmTargets/statistics.py
- DirectDmTargets/utils.py
- notebooks/load_results_multinest.py
- scripts/run_combined_multinest
- setup.cfg
- setup.py
- tests/test_detectors.py
- tests/test_emcee_sampler.py
- tests/test_multinest_combined.py
- tests/test_multinest_shielded.py
- tests/test_nested_samplers.py
- tests/test_nestle_shielded.py
- tests/test_plots.py
- tests/test_several.py
- tests/test_spectra.py
In this PR:
- Fix emcee sampler to run with self.config instead of self.fit_params
- Fix subdirs of the _pids 
- Add few tests for previously not-covered code.
- Restructure scripts
> update to run locally

- .bumpversion.cfg
- DirectDmTargets/__init__.py
- HISTORY.rst
- setup.py
In this PR, we create version 1.0.0 of DirectDmTargets
> Create new release, v1.0.0

- DirectDmTargets/utils.py
one common logger for simplicity
> Add a logger with nice formatting

- DirectDmTargets/plot_basics.py
Allow pickle saving and loading of canvas to load files.
> Save canvas to pickle

- DirectDmTargets/detector.py
Use the resolution from this paper for the resolution of xenon1T:
https://journals.aps.org/prd/pdf/10.1103/PhysRevD.102.072004
> Use 1T low-er resolution

- DirectDmTargets/detector.py
See table V
https://arxiv.org/pdf/1610.00006.pdf
> Fix Ge-iZIP background rate

- DirectDmTargets/detector.py
Fix issue https://github.com/jorana/DirectDmTargets/issues/54 with more up to date parameters
> fix #54 - Update XENONnT 

- DirectDmTargets/__init__.py
- DirectDmTargets/confidence_figures.py
- DirectDmTargets/plot_basics.py
- DirectDmTargets/statistics.py
- DirectDmTargets/utils.py
- tests/test_multinest_combined.py
Add code for making result plots
> add result plotting

- .github/workflows/auto_pep8.yml
- DirectDmTargets/confidence_figures.py
- DirectDmTargets/detector.py
- DirectDmTargets/statistics.py
- scripts/run_combined_multinest
- scripts/run_dddm_emcee
- tests/test_1d_likelihood.py
> restort autopep8

- DirectDmTargets/confidence_figures.py
- DirectDmTargets/detector.py
- DirectDmTargets/halo.py
- DirectDmTargets/nested_sampling.py
- DirectDmTargets/statistics.py
- DirectDmTargets/utils.py
- scripts/run_combined_multinest
- tests/test_multinest_combined.py
In `run_combined_multinest` there was an error that set the experiment to be of the combined type, even if the experiment existed
> fixes to #87

- DirectDmTargets/detector.py
- tests/test_multinest_combined.py
- tests/test_multinest_shielded.py
- tests/test_nested_samplers.py
- tests/test_nestle_shielded.py
In #87 , one aspect was overlooked in fixing the detector class. This is that we first need to apply the resolution, followed by the smearing.
> first apply smearing, then the threshold

- .github/scripts/install_on_linux.sh
- .github/workflows/test_package.yml
Renamed the package from DirectDmTargets -> dddm, causing failures in automated testing since:
> Fix name change of package

- DirectDmTargets/statistics.py
- scripts/run_combined_multinest
- submit_to_stoomboot/write_script.py
Allow fixed prior ranges to be set and not be adjusted
> add fixed prior ranges

- DirectDmTargets/confidence_figures.py
- DirectDmTargets/context.py
- DirectDmTargets/emcee_applications.py
- DirectDmTargets/nested_sampling.py
- DirectDmTargets/seaborn_utils.py
- DirectDmTargets/utils.py
- extra_requirements/requirements-tests.txt
- tests/test_1d_likelihood.py
- tests/test_deprecated.py
- tests/test_emcee_sampler.py
- tests/test_multinest_combined.py
- tests/test_seaborn_utils.py
Add some tests, delete some old code
> try upping coverage

- tests/test_multinest_combined.py
> Increase testing stability

- .coveragerc
small tweak to up coverage since `raise Bla` is not something that is worth testing in general
> ignore raise in coverage

- dddm/plotting/confidence_figures.py
> string formatting tweaks for lin log scales

- dddm/detectors/super_cdms_darkelf.py
set the energy range of Si/Ge targets to 0, 1 keV since dark elf mostly predicts low-energy recoils
> Semiconductor experiments energy range

- requirements.txt
> Drop direct numpy dependency, fix #259

- extra_requirements/requirements-base.txt
- extra_requirements/requirements-tests.txt
Fix failing tests by using next version of ultranest
https://github.com/JohannesBuchner/UltraNest/pull/104
> Use newer `ultranest` & `vegas` for `cython 3`

- .readthedocs.yml
Implement fix due to changes in read the docs api
https://github.com/readthedocs/readthedocs.org/issues/8912
> Fix doc building
